language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

before_install:
  - docker --version

script:
  - cat /dev/null > template_src/hooks/android/before_build.js
  - docker build --pull -f ci/Dockerfile.android --rm -t cordova-template-cesium .
