FROM alvisisme/cordova-android:9.0.0
COPY . /template
RUN cordova create myapp --template /template \
    && cd myapp \
    && yarn install \
    && yarn build \
    && cordova platform add android \
    && cordova prepare android \
    && cordova build android